@echo off
cd python
python task.py clearOutput buildScripts buildResources compileNativeRelease updateClasspath compileJavaRelease buildAdditional buildInfo excludeDirectories buildPackage cleanupOutput