@echo off
cd python
python task.py clearOutput buildScripts buildResources compileNativeDebug updateClasspath compileJavaDebug buildAdditional buildInfo cleanupOutput stopHorizon pushEverything launchHorizon
